name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install
        run: npm i
      - name: Cypress Install
        run: npm i cypress @percy/cypress @percy/cli
      - name: Percy Test
        run: percy exec -- npm run cy:run
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
